# Generated by Django 2.2 on 2020-07-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperiod',
            name='tz',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tz',
            field=models.CharField(default='America/Los_Angeles', max_length=255),
            preserve_default=False,
        ),
    ]
